// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHoFXod2OoWICcIPmwxI633InHxzMWtqg',
    appId: '1:878391700420:web:8cf48a5fa6687a24355291',
    messagingSenderId: '878391700420',
    projectId: 'eofficedeskaccurabad',
    authDomain: 'eofficedeskaccurabad.firebaseapp.com',
    storageBucket: 'eofficedeskaccurabad.appspot.com',
    measurementId: 'G-JBEPQ339GV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFCLdekd9CT35Zpa9pxP33SOC9W5uuFho',
    appId: '1:878391700420:android:2783eda29638e545355291',
    messagingSenderId: '878391700420',
    projectId: 'eofficedeskaccurabad',
    storageBucket: 'eofficedeskaccurabad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADVT2Nyjc-8z-VHoVLd7svsVvoDGm0mBU',
    appId: '1:878391700420:ios:b8f0a1d2c9914378355291',
    messagingSenderId: '878391700420',
    projectId: 'eofficedeskaccurabad',
    storageBucket: 'eofficedeskaccurabad.appspot.com',
    iosClientId: '878391700420-7aunv6bqo50s268aldto8ocsk7rdj3f1.apps.googleusercontent.com',
    iosBundleId: 'com.accurabad.sharvaya',
  );
}
